version: '3.8'

services:
  app:
    build: .
    image: asweproj.azurecr.io/c2
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_USER: springuser
      MYSQL_DATABASE: appdb
      MYSQL_PASSWORD_FILE: /mnt/secrets/MYSQL_PASSWORD
    secrets:
      - source: mysql_password
        target: /mnt/secrets/MYSQL_PASSWORD

  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD_FILE: /mnt/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /mnt/secrets/mysql_root_password
    secrets:
      - source: mysql_password
        target: /mnt/secrets/mysql_password
      - source: mysql_root_password
        target: /mnt/secrets/mysql_root_password

  reverse-proxy:
    build: ./caddy
    image: asweproj.azurecr.io/reverse-proxy
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mysql-data:
    driver: azure_file
    driver_opts:
      share_name: acishare
      storage_account_name: asweprojstorage

secrets:
  mysql_password:
    file: ./mysql_password.txt
  mysql_root_password:
    file: ./mysql_root_password.txt