version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
        environment:
          MYSQL_HOST: localhost 
          MYSQL_DATABASE: appdb
          MYSQL_USER: springuser
          MYSQL_PASSWORD: springusersecret
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootsecret
          MYSQL_HOST: localhost
          MYSQL_DATABASE: appdb
          MYSQL_USER: springuser
          MYSQL_PASSWORD: springusersecret
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Wait for Database Port
          command: while ! nc -z localhost 3306 ; do sleep 1 ; done
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path:  target
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=reffians_aswe-proj
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh -oStrictHostKeyChecking=no -v $USER@$HOST "./deploy.sh"


workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          context: SonarCloud
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main

